import AnimatePresenceMotion from "@/components/UI/AnimatePresenceMotion/page";
import "./globals.css";
import { Oswald } from "next/font/google";

const fontUsed = Oswald({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AnimatePresenceMotion>
        <body
          style={{ WebkitTapHighlightColor: "transparent" }}
          className={fontUsed.className}
        >
          {children}
        </body>
      </AnimatePresenceMotion>
    </html>
  );
}
